repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # - id: no-commit-to-branch # prevent direct commits to main branch
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        types: [python]
        args: [--strict]

  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: make
        args: [lint]
        types: [python]
        language: system
      - id: ruff format
        name: Ruff Format
        entry: make
        args: [format]
        language: system
        types: [python]
      # - id: pyright
      #   name: pyright
      #   entry: rye
      #   language: system
      #   args: ["run", "typecheck"]
      #   types: [python]
      #   pass_filenames: false
